#!/bin/sh

# PROVIDE: JokerCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# JokerCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable JokerCoin service.
# JokerCoin_config (path): Set to /usr/local/etc/JokerCoin.conf by default.
# JokerCoin_user:  The user account JokerCoin daemon runs as. It uses 'root' user by default.
# JokerCoin_group: The group account JokerCoin daemon runs as. It uses 'wheel' group by default.
# JokerCoin_datadir (str): Default to "/var/db/JokerCoin". Base data directory.

. /etc/rc.subr

name=JokerCoin
rcvar=JokerCoin_enable

: ${JokerCoin_enable:=NO}
: ${JokerCoin_config=/usr/local/etc/JokerCoin.conf}
: ${JokerCoin_datadir=/var/db/JokerCoin}
: ${JokerCoin_user="root"}
: ${JokerCoin_group="wheel"}

required_files=${JokerCoin_config}
command=/usr/local/bin/JokerCoind
JokerCoin_chdir=${JokerCoin_datadir}
pidfile="${JokerCoin_datadir}/JokerCoind.pid"
stop_cmd=JokerCoin_stop
command_args="-conf=${JokerCoin_config} -datadir=${JokerCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

JokerCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${JokerCoin_datadir}
	[ $? -eq 0 ] && chown -R ${JokerCoin_user}:${JokerCoin_group} ${JokerCoin_datadir}
}

JokerCoin_prestart()
{
	if [ ! -d "${JokerCoin_datadir}/." ]; then
		JokerCoin_create_datadir || return 1
	fi
}

JokerCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

JokerCoin_stop()
{
    JokerCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${JokerCoin_config} -datadir=${JokerCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
